### ISSUE TITLE
Target of subproject is packaged in stubs

### ISSUE THREAD

**Issue by wesaidso** [spring-cloud-samples/spring-cloud-contract-samples#1]
When the project ```spring-cloud-contract-samples/beer_contracts/src/main/resources/contracts/com/example/beer-api-producer-external``` is build and after that the top level project ```spring-cloud-contract-samples/beer_contracts``` is build then the target dir of the sub project is packaged in the stubs jar. 

The structure then looks like this:
<pre>
.
├── com
│   └── example
│       └── beer-api-producer-external
│           ├── beer-api-consumer
│           │   ├── messaging
│           │   │   ├── shouldSendAcceptedVerification.groovy
│           │   │   └── shouldSendRejectedVerification.groovy
│           │   └── rest
│           │       ├── shouldGrantABeerIfOldEnough.groovy
│           │       └── shouldRejectABeerIfTooYoung.groovy
│           ├── pom.xml
│           └──**target**
│               ├── generated-test-sources
│               │   ├── contracts
│               │   │   └── org
│               │   │       └── springframework
│               │   │           └── cloud
│               │   │               └── contract
│               │   │                   └── verifier
│               │   │                       └── tests
│               │   │                           └── beer_api_consumer
│               │   │                               ├── MessagingTest.java
│               │   │                               └── RestTest.java
│               │   └── test-annotations
│               ├── maven-status
│               │   └── maven-compiler-plugin
│               │       └── testCompile
│               │           └── default-testCompile
│               │               ├── createdFiles.lst
│               │               └── inputFiles.lst
│               ├── stubs
│               │   ├── contracts
│               │   │   ├── beer-api-consumer
│               │   │   │   ├── messaging
│               │   │   │   │   ├── shouldSendAcceptedVerification.groovy
│               │   │   │   │   └── shouldSendRejectedVerification.groovy
│               │   │   │   └── rest
│               │   │   │       ├── shouldGrantABeerIfOldEnough.groovy
│               │   │   │       └── shouldRejectABeerIfTooYoung.groovy
│               │   │   ├── pom.xml
│               │   │   └── **target**
│               │   │       └── generated-test-sources
│               │   │           └── contracts
│               │   │               └── org
│               │   │                   └── springframework
│               │   │                       └── cloud
│               │   │                           └── contract
│               │   │                               └── verifier
│               │   │                                   └── tests
</pre>

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/89a2aa7a66692a38ff275d6ac488444346b94a60
