### ISSUE TITLE
Do you have any example about  Scenario 2 (output triggered by input)

### ISSUE THREAD

**Issue by jeven2016** [spring-cloud-samples/spring-cloud-contract-samples#10]
Hi,
Do you have any example about  Scenario 2 (output triggered by input), thanks.

```
Contract.make {
	label 'return_book_2'
	input {
		messageFrom('jms:input')
		messageBody([
				bookName: 'foo'
		])
		messageHeaders {
			header('sample', 'header')
		}
	}
	outputMessage {
		sentTo('jms:output')
		body([
				bookName: 'foo'
		])
		headers {
			header('BOOK-NAME', 'foo')
		}
	}
}
```

I still failed to pass the generated tests in producer side.....

validate_should_fail_update_reachability
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'topicName' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:687)
	at 

Thanks,
Jeven

**Comment by marcingrzejszczak** [comment]
Hi Jeven! Two things. One I think that we have to remove those two types of contracts (check this out https://github.com/spring-cloud/spring-cloud-contract/issues/321). Two - if you have such an exception that means that you're missing a channel. Are you sure you have the `@EnableBinding(Source.class, Sink.class)` ?

**Comment by OlgaMaciaszek** [comment]
Hello @jeven2016 have you managed to make it work or do you still need help with this?
