### ISSUE TITLE
Test if prepareForWorkshops produce code that compiles

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud-samples/spring-cloud-contract-samples#11]

**Comment by jtig** [comment]
producer/build.gradle has too many lines removed when invoking prepareForWorkshops

**Comment by marcingrzejszczak** [comment]
Can you write which lines exactly got removed and shouldn't? It will be
easier to fix it if you provide more info

**Comment by marcingrzejszczak** [comment]
should be fixed by https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/058d699feb736ed93d0717e7e1ffd288d6876ea0
