### ISSUE TITLE
Workshop is not consistent

### ISSUE THREAD

**Issue by paul-ovchinnikov** [spring-cloud-samples/spring-cloud-contract-samples#120]
I spent 2 days to go through the simplest examples. The reason for this is that the description and code examples do not match. The workshop samples code also does not match the documentation. I will not give specific examples, there are many of them. Just try out a few lessons yourself.

**Comment by paul-ovchinnikov** [comment]
producer_with_restdoc sample, .pom file assembly plugin adding
documentation sample:
```
<configuration>
    <attach>true</attach>
    <descriptor>${basedir}/src/assembly/stub.xml</descriptor>
</configuration>
```
missing `<descriptors>` tag
There are a lot of such stupid mistakes in workshop

**Comment by paul-ovchinnikov** [comment]
Spring Cloud Contract with Rest Docs Workshop:
- Writing Your First Rest Docs Test - fails due to AssertJ incompatible version
- Generating Tests from Contracts - does not generate anything under /target/generated-test-sources

**Comment by marcingrzejszczak** [comment]
Thanks for the info

**Comment by marcingrzejszczak** [comment]
Are you willing to file a PR to help?

**Comment by marcingrzejszczak** [comment]
We're no longer supporting the workshops.
