### ISSUE TITLE
Can't generate test code in producer-external project

### ISSUE THREAD

**Issue by AlexWei2013** [spring-cloud-samples/spring-cloud-contract-samples#13]
I try to learn it on local, I created the beer-contracts project as external contracts and installed the jar(beer-contracts) to .m2.   Also, I added the jar to producer- external project. all are OK.
But when I run the test for producer- external, I found no contracts 'stest code in generated-test-sources folder.  I don't change the code. where is wrong. please help. 

log info:

```
[INFO] --- spring-cloud-contract-maven-plugin:1.1.1.RELEASE:generateTests (default-generateTests) @ beer-api-producer-external ---
[INFO] Generating server tests source code for Spring Cloud Contract Verifier contract verification
[INFO] Download dependency is provided - will download contract jars
[INFO] Will download contracts from [null]. Work offline switch equals to [true]
[INFO] Remote repos not passed but the switch to work offline was set. Stubs will be used from your local Maven repository.
[INFO] Will download contracts for [com.example:beer-contracts:+:]
[INFO] Desired version is [+] - will try to resolve the latest version
[INFO] Resolved version is [0.0.1-SNAPSHOT]
[INFO] Resolving artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] using remote repositories []
[INFO] Resolved artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] to C:\Users\Administrator\.m2\repository\com\example\beer-contracts\0.0.1-SNAPSHOT\beer-contracts-0.0.1-SNAPSHOT.jar
[INFO] Unpacking stub from JAR [URI: file:/C:/Users/Administrator/.m2/repository/com/example/beer-contracts/0.0.1-SNAPSHOT/beer-contracts-0.0.1-SNAPSHOT.jar]
[INFO] Unpacked file to [C:\Users\ADMINI~1\AppData\Local\Temp\contracts564556852322903495]
[INFO] Pattern to pick contracts equals [^C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\contracts564556852322903495\\com\\example\\beer-api-producer-external\\.*$]
[INFO] Ant Pattern to pick files equals [**\com/example/beer-api-producer-external\**/]
[INFO] Directory with contract is present at [C:\Users\ADMINI~1\AppData\Local\Temp\contracts564556852322903495]
[INFO] Test Source directory: D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts added.
[INFO] Using null as base class for test classes
[INFO] Generated 0 test classes.
```

**Comment by marcingrzejszczak** [comment]
Interesting. Most likely it's the case of Windows File separator. This `Ant Pattern to pick files equals [**\com/example/beer-api-producer-external\**/]` looks strange... I filed an issue -
 https://github.com/spring-cloud/spring-cloud-contract/issues/349 - will try to fix it but honestly, I don't have a windows box to test it...

**Comment by marcingrzejszczak** [comment]
Try it out with latest snapshots

**Comment by AlexWei2013** [comment]
spring cloud contract 1.1.2 snapshots？

**Comment by marcingrzejszczak** [comment]
Yeah it can be `1.1.2.BUILD-SNAPSHOT`.

**Comment by AlexWei2013** [comment]
It look like  can't download the spring-cloud-contract-maven-plugin 1.1.2.BUILD-SNAPSHOT.

**Comment by AlexWei2013** [comment]
Good, it look can generate the contract for test code. but it have a bit strange about folder. like:
[INFO] --- spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests (default-generateTests) @ beer-api-producer-external ---
[INFO] Generating server tests source code for Spring Cloud Contract Verifier contract verification
[INFO] Download dependency is provided - will download contract jars
[INFO] Will download contracts from [null]. Work offline switch equals to [true]
[INFO] Remote repos not passed but the switch to work offline was set. Stubs will be used from your local Maven repository.
[INFO] Will download contracts for [com.example:beer-contracts:+:]
[INFO] Desired version is [+] - will try to resolve the latest version
[INFO] Resolved version is [0.0.1-SNAPSHOT]
[INFO] Resolving artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] using remote repositories []
[INFO] Resolved artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] to C:\Users\Administrator\.m2\repository\com\example\beer-contracts\0.0.1-SNAPSHOT\beer-contracts-0.0.1-SNAPSHOT.jar
[INFO] Unpacking stub from JAR [URI: file:/C:/Users/Administrator/.m2/repository/com/example/beer-contracts/0.0.1-SNAPSHOT/beer-contracts-0.0.1-SNAPSHOT.jar]
[INFO] Unpacked file to [C:\Users\ADMINI~1\AppData\Local\Temp\contracts550902087664221218]
[INFO] Will pick a pattern from group id and artifact id
[INFO] Pattern to pick contracts equals [^C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\contracts550902087664221218(\\)?.*com\\example\\beer-api-producer-external\\.*$]
[INFO] Ant Pattern to pick files equals [**/com/example/beer-api-producer-external/**/]
[INFO] Directory with contract is present at [C:\Users\ADMINI~1\AppData\Local\Temp\contracts550902087664221218]
[INFO] Test Source directory: D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts added.
[INFO] Using null as base class for test classes
[INFO] Creating new class file [D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts\com\example\beer-api-producer-external**\1\0\0\**beer-api-consumer\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\RestTest.java]
[INFO] Creating new class file [D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts\com\example\beer-api-producer-external**\1\0\0\**beer-api-consumer\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\MessagingTest.java]
[INFO] Generated 2 test classes.

**Comment by AlexWei2013** [comment]
Good, it look is OK as the below: but, the folder "generated-test-sources\contracts\com\example\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\RestTest.java]" have two "contracts\com\example".  is it OK? how to remove one?

```
[INFO] --- spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests (default-generateTests) @ beer-api-producer-external ---
[INFO] Generating server tests source code for Spring Cloud Contract Verifier contract verification
[INFO] Download dependency is provided - will download contract jars
[INFO] Will download contracts from [null]. Work offline switch equals to [true]
[INFO] Remote repos not passed but the switch to work offline was set. Stubs will be used from your local Maven repository.
[INFO] Will download contracts for [com.example:beer-contracts:+:]
[INFO] Desired version is [+] - will try to resolve the latest version
[INFO] Resolved version is [0.0.1-SNAPSHOT]
[INFO] Resolving artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] using remote repositories []
[INFO] Resolved artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] to C:\Users\Administrator\.m2\repository\com\example\beer-contracts\0.0.1-SNAPSHOT\beer-contracts-0.0.1-SNAPSHOT.jar
[INFO] Unpacking stub from JAR [URI: file:/C:/Users/Administrator/.m2/repository/com/example/beer-contracts/0.0.1-SNAPSHOT/beer-contracts-0.0.1-SNAPSHOT.jar]
[INFO] Unpacked file to [C:\Users\ADMINI~1\AppData\Local\Temp\contracts3013098898008194869]
[INFO] Will pick a pattern from group id and artifact id
[INFO] Pattern to pick contracts equals [^C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\contracts3013098898008194869(\\)?.*com\\example\\beer-api-producer-external\\.*$]
[INFO] Ant Pattern to pick files equals [**/com/example/beer-api-producer-external/**/]
[INFO] Directory with contract is present at [C:\Users\ADMINI~1\AppData\Local\Temp\contracts3013098898008194869]
[INFO] Test Source directory: D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts added.
[INFO] Using null as base class for test classes
[INFO] Creating new class file [D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts\com\example\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\RestTest.java]
[INFO] Creating new class file [D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts\com\example\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\MessagingTest.java]
[INFO] Generated 2 test classes.
```

**Comment by AlexWei2013** [comment]
Good. it is OK. as the log. but the generated folder "generated-test-sources\contracts\com\example\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\RestTest.java]" have two "\contracts\com\example\". is it OK? how to remove one?

```
[INFO] --- spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests (default-generateTests) @ beer-api-producer-external ---
[INFO] Generating server tests source code for Spring Cloud Contract Verifier contract verification
[INFO] Download dependency is provided - will download contract jars
[INFO] Will download contracts from [null]. Work offline switch equals to [true]
[INFO] Remote repos not passed but the switch to work offline was set. Stubs will be used from your local Maven repository.
[INFO] Will download contracts for [com.example:beer-contracts:+:]
[INFO] Desired version is [+] - will try to resolve the latest version
[INFO] Resolved version is [0.0.1-SNAPSHOT]
[INFO] Resolving artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] using remote repositories []
[INFO] Resolved artifact [com.example:beer-contracts:jar:0.0.1-SNAPSHOT] to C:\Users\Administrator\.m2\repository\com\example\beer-contracts\0.0.1-SNAPSHOT\beer-contracts-0.0.1-SNAPSHOT.jar
[INFO] Unpacking stub from JAR [URI: file:/C:/Users/Administrator/.m2/repository/com/example/beer-contracts/0.0.1-SNAPSHOT/beer-contracts-0.0.1-SNAPSHOT.jar]
[INFO] Unpacked file to [C:\Users\ADMINI~1\AppData\Local\Temp\contracts3013098898008194869]
[INFO] Will pick a pattern from group id and artifact id
[INFO] Pattern to pick contracts equals [^C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\contracts3013098898008194869(\\)?.*com\\example\\beer-api-producer-external\\.*$]
[INFO] Ant Pattern to pick files equals [**/com/example/beer-api-producer-external/**/]
[INFO] Directory with contract is present at [C:\Users\ADMINI~1\AppData\Local\Temp\contracts3013098898008194869]
[INFO] Test Source directory: D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts added.
[INFO] Using null as base class for test classes
[INFO] Creating new class file [D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts\com\example\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\RestTest.java]
[INFO] Creating new class file [D:\ideaProjects\producer_with_external_contracts\target\generated-test-sources\contracts\com\example\contracts\com\example\beer_api_producer_external\1_0_0\beer_api_consumer\MessagingTest.java]
[INFO] Generated 2 test classes.
```

**Comment by marcingrzejszczak** [comment]
Interesting - you'd have to show me the structure of the JAR with contracts

**Comment by AlexWei2013** [comment]
the structure of [beer-contracts] is like in respository
\.m2\repository\com\example\beer-contracts\0.0.1-SNAPSHOT\beer-contracts-0.0.1-SNAPSHOT.jar

the structure of beer-contracts-0.0.1-SNAPSHOT.jar is like:
contracts\com\example\beer-api-producer-external\1.0.0\beer-api-consumer\rest

**Comment by marcingrzejszczak** [comment]
Strange... but most important thing is that it's working ;)

**Comment by AlexWei2013** [comment]
Yeah， Thinks ~\(≧▽≦)/~
