### ISSUE TITLE
Compilation failed as no suitable method found for convertAsCollection

### ISSUE THREAD

**Issue by GabbyChang** [spring-cloud-samples/spring-cloud-contract-samples#15]
While I build beer_contracts, it's always failed as contract.verifier error.
Here is the error:
[INFO] Reactor Summary:
[INFO]
[INFO] Common ............................................. SUCCESS [  3.610 s]
[INFO] Contracts .......................................... FAILURE [  1.585 s]
[INFO] Producer ........................................... SKIPPED
[INFO] Producer ........................................... SKIPPED
[INFO] Producer ........................................... SKIPPED
[INFO] Producer With External Contracts ................... SKIPPED
[INFO] Producer With Rest Docs ............................ SKIPPED
[INFO] Consumer ........................................... SKIPPED
[INFO] Consumer ........................................... SKIPPED
[INFO] Consumer ........................................... SKIPPED
[INFO] Consumer with Rest Docs ............................ SKIPPED
[INFO] Spring Cloud Contract Samples ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.788 s
[INFO] Finished at: 2017-07-24T16:00:25+08:00
[INFO] Final Memory: 75M/486M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project beer-contracts: Compilation failure
[ERROR] /C:/git/spring-cloud-contract-samples/beer_contracts/src/test/java/docs/GenerateAdocsFromContractsTests.java:[87,78] no suitable method found for convertAsCollection(java.io.File,java.io.File)
[ERROR]     method org.springframework.cloud.contract.verifier.util.ContractVerifierDslConverter.convertAsCollection(java.lang.String) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     method org.springframework.cloud.contract.verifier.util.ContractVerifierDslConverter.convertAsCollection(java.io.File) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]
[ERROR] -> [Help 1]

POM information: 
<spring-cloud.version>Dalston.SR1</spring-cloud.version>
<spring-cloud-contract.version>1.1.1.RELEASE</spring-cloud-contract.version>

**Comment by marcingrzejszczak** [comment]
That's because you're using RELEASE stuff and I've modified the project to use the snapshot features. If you check out the branches then you have `2.0.x` for `2.0.x` version of SC-Contract, `1.1.x` for `1.1.x` version of SC-Contract and `master` for `1.2.x` version of SC-Contract. Please update the versions not of `master` branch but `1.1.x` branch and try again
