### ISSUE TITLE
Does contract can support Chinese

### ISSUE THREAD

**Issue by Pastel001** [spring-cloud-samples/spring-cloud-contract-samples#17]
My contract response contains Chinese like this
` response {
        status 200
        body("""
            {
                "code": 91015,
                "description": "订单已失效",
                "lastUpdateTime": "0",
                "payload": null
            }
        """)
    }`
and the generated mapping json like this
`"response" : {
    "status" : 200,
    "body" : "{\"code\":91015,\"description\":\"\\u8ba2\\u5355\\u5df2\\u5931\\u6548\",\"lastUpdateTime\":\"0\",\"payload\":null}",
    "transformers" : [ "response-template" ]
  }`
So,i want to know how to set the encoding for contract file? dose it can set utf-8?
how can i find the contract file learning materials?
Thank you

**Comment by marcingrzejszczak** [comment]
This repository is only for samples not for Spring Cloud Contract support. 

Here you have the project page - https://cloud.spring.io/spring-cloud-contract/
Here you have the project repository - https://github.com/spring-cloud/spring-cloud-contract

Please file an issue in Spring Cloud Contract repository. Also provide more information - do the generated tests also get improperly created? Please provide the contract version, your project setup and the whole contract.

Also could you please read this section of Github formatting - https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/ . You can put ``` around the snippet to properly format it. 

Thanks ! :)

**Comment by Pastel001** [comment]
Thanks for your suggest.
I shoud Try to learn more and i know this repository is about samples.
I shoud not ask here. Thanks for your answer
