### ISSUE TITLE
Working example of gradle multimodule project

### ISSUE THREAD

**Issue by klubi** [spring-cloud-samples/spring-cloud-contract-samples#179]
I'm struggling for some time now, to properly setup `@AutoConfigureStubRunner` annotation to pull my groovy contract files from different module in gradle multimodule project.

Relation of test to raw contracts looks like this:
```
|--contracts/src/test/resources/contracts/com.foo/BarContract.groovy
|--src/test/groovy/com.foo.domain/BarSpec.groovy
```

Below annotation does not work...
```java
@AutoConfigureStubRunner(stubsMode = StubsMode.REMOTE,
    repositoryRoot = "stubs://file://contracts/src/test/resources/contracts",
    ids = "com.foo",
    generateStubs = true)
```

I'm using 2.2.5.RELEASE versions of gradle plugin, and stub-runner.

Moreover, when I run my test I get below exception:
```
o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'batchStubRunnerBeanPostProcessor' defined in class path resource [org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.class]: Unsatisfied dependency expressed through method 'batchStubRunnerBeanPostProcessor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchStubRunner' defined in class path resource [org/springframework/cloud/contract/stubrunner/spring/StubRunnerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.stubrunner.BatchStubRunner]: Factory method 'batchStubRunner' threw exception; nested exception is java.lang.IllegalStateException: No stubs were found on classpath for [:]
```

Working example of such setup would be helpful.

**Comment by marcingrzejszczak** [comment]
Your path is wrong. Check this example https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/f0564234288dde4bb436a29231b1bf7539f71494/consumer_with_latest_2_2_features/src/test/java/com/example/GenerateStubsTest.java#L28

**Comment by klubi** [comment]
Can you be more specific? Which part of path is wrong?
If it's because it's missing `System.getenv("ROOT")` part then suggested solution won't work with `@AutoConfigureStubRunner` annotation because it requires path to be inline constant.

![image](https://user-images.githubusercontent.com/4123293/100594765-643f1280-32fa-11eb-9723-e5c4493e6460.png)

**Comment by marcingrzejszczak** [comment]
Ah true, I've pointed you to a rule, sorry.

At the time being we don't support such resolution for the annotation (can you please double check that this doesn't work `"stubs://file://#{systemEnvironment['ROOT']/producer_with_latest_2_2_features/src/test/resources/contracts/beer/in_progress"` ? If that's the case you should use the Rule / Extension instead of an annotation until now and please file an enhancement request in spring-cloud-contract project.

**Comment by klubi** [comment]
String templating does not work in this case either.

I'll file a ticket for that. 
Thanks
