### ISSUE TITLE
About version controls.

### ISSUE THREAD

**Issue by blazersoft** [spring-cloud-samples/spring-cloud-contract-samples#19]
Hello.

May I have a question if u don't mind ?

When a version of producer API is changed such as a changing contract spec, how to recognise and remind consumer side if it is in a team project or some connected micro-services ? 

I mean, i wanna know about version control of contract's specs.

Thanks in advance.

**Comment by marcingrzejszczak** [comment]
Hi! I don't seem to understand exactly what you mean... Can you elaborate more on this topic? Also, there is a section about API / stubs versioning here http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_how_to_do_stubs_versioning but I don't know if it's what you are asking about actually.

**Comment by blazersoft** [comment]
Hi~, Thank you for answering this question. 
Your answer contains some part of what i have wanted to know. It's helpful as well.  I am very appreciated about that.
And, I also think it seems to be confusing as you said. I think it's not about a version control. sorry, I mean, I just want to know that some way (or tools) how to remind colleagues or a co-work team such as development-team (consumer side) to notice about changing information of contract's spec (producer side). it's like adding some variables to request parameters or response's return elements normally.

Actually, I have been researching idle way to manage spec of contract. I am using remote maven repository and jenkins pipeline to build and test automatically by using your spring-cloud-contract project. 

I just want to some advises, when you usually have to change or update the library and a developer of consumer side should modify the dependencies, how to notify or co-work.

Even if this question would be ridiculous, Thank you very much for your response indeed.

**Comment by marcingrzejszczak** [comment]
The question is not ridiculous :)

What you can do is to do 3 things.

- *We want the consumers to see immediately the changes of the contract* - start producing snapshot stubs from the producer side. The consumers will reuse the snapshot dependencies and can be built in a scheduled manner (for example build every 3 hours). That way you will catch any changes that happened on the producer side
- *Produce documentation of your contracts* - on the producer side you can have a test (example here https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/beer_contracts/src/test/java/docs/GenerateAdocsFromContractsTests.java) that builds an Asciidoctor file from your contract definitions. Then you can convert those with an Asciidoctor plugin to HTML and upload your API definition.
- *Backward compatibility check from the producer perspective* - We don't want to publish backward incompatible changes. Check Spring Cloud Pipelines where we describe how to do that (https://cloud.spring.io/spring-cloud-pipelines/single/spring-cloud-pipelines.html#_build) . And here you have an example of Maven setup - https://github.com/spring-cloud-samples/github-webhook/blob/master/pom.xml#L140-L178 and here of Gradle one (`contracts` section - https://github.com/spring-cloud-samples/github-analytics/blob/master/build.gradle#L50-L69 and the task https://github.com/spring-cloud-samples/github-analytics/blob/master/gradle/pipeline.gradle#L22-L29)

Does it make sense?

**Comment by blazersoft** [comment]
Yes, it makes sense very much. It's very helpful for me.
I'm gonna close this issue.
Thank for your help.  :-)
