### ISSUE TITLE
How to properly import gradle project to IntelliJ?

### ISSUE THREAD

**Issue by Kinmarui** [spring-cloud-samples/spring-cloud-contract-samples#20]
Could you describe how to import this project to IntelliJ so I would have full idea support out of box? I tried adding `apply plugin: 'idea'` to top level build.gradle and reimporting project but without success.

Currently Intellij doesn't understand folder structure (no sources/resources or main/test markings on directories) and when I add it manually using `mark directory as` IntelliJ cannot find proper gradle dependencies / dependencies on other submodules (i,e beer_contracts)

**Comment by marcingrzejszczak** [comment]
Just import the `pom` / `build.gradle` . Don't do any applications of `idea` plugin.

**Comment by Kinmarui** [comment]
I've done it using config shown on first screenshot and I can see gradle tasks in gradle window (even those in workshop group) but code completion for code doesn't work anywhere and I think it is related to fact that intellij doesn't marks source directories as source etc (shown on second screenshot) I've marked java in `src/main` manually, but all directories after import have gray color.
![image](https://user-images.githubusercontent.com/3742151/31905680-47be2982-b82f-11e7-90cf-a8e2dff00d85.png)
![image](https://user-images.githubusercontent.com/3742151/31905876-ce264d7e-b82f-11e7-86f9-10c032a1d40b.png)

**Comment by Kinmarui** [comment]
part of fixing problem with gradle import is adding settings.gradle to let know intellij that this is multi-module project see https://github.com/spring-cloud-samples/spring-cloud-contract-samples/pull/21

**Comment by marcingrzejszczak** [comment]
Now I remember... This project was never intended to be imported with Gradle. The Gradle setup is only to generate workshops etc. 

No problem :) Hopefully, you're enjoying it!
