### ISSUE TITLE
how to mock the service

### ISSUE THREAD

**Issue by arat3091** [spring-cloud-samples/spring-cloud-contract-samples#206]
In the real world there is always a dependency  inside the controller. How to mock that service and then inject into the controller and then use that controller while starting server.

With the current example the dependency will be null always and hence 500 will be the response

**Comment by marcingrzejszczak** [comment]
You have all sort of examples in the spring-cloud-contract-samples repository. Services are being injected into controllers as mocks either as Spring beans or manually. You can teach those mocks to behave accordingly.
