### ISSUE TITLE
Acknowledgment to producer 

### ISSUE THREAD

**Issue by dvsgvarma** [spring-cloud-samples/spring-cloud-contract-samples#22]
Is there a way to notify **producer** that the contract has failed for some of his **consumers** for some **reason** ("Some this which cannot be modified from consumer side")

Main idea is to know all client failure reasons to initiate a discussion

**Comment by marcingrzejszczak** [comment]
I don't really understand what you mean. Can you elaborate on this?

**Comment by marcingrzejszczak** [comment]
I'm closing this cause it has nothing to do with the samples
