### ISSUE TITLE
Spring-boot-starter-test dependecy missing in build.gradle file (consumer project)

### ISSUE THREAD

**Issue by amirensit** [spring-cloud-samples/spring-cloud-contract-samples#267]
**Describe the bug**
I cloned the samples in my laptop in order to learn about spring cloud contract project. I noticed that the starter for test is missing (In my case I imported  as gradle project, the dependency is present in pom.xml file).

**Solution**
Just I added the dependency in build.gradle and It works. I am able now to proceed with the intersting workshop 😃

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/spring-cloud-samples/spring-cloud-contract-samples/issues/267#event-5006047611
