### ISSUE TITLE
Cannot run maven build on any example

### ISSUE THREAD

**Issue by rezekdan** [spring-cloud-samples/spring-cloud-contract-samples#405]
**Describe the bug**
* Fresh checkout
* tried to run `./scripts/runMavenBuilds.sh`
* pretty much every example results in the same error message: see below for a sample

**Sample**
```
...
[ERROR]   The project com.example:beer-api-consumer-java:0.0.1-SNAPSHOT (/home/.../spring-cloud-samples/spring-cloud-contract-samples/consumer_java/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-stream:test-jar:test-binder is missing. @ line 61, column 15
...
```

not sure if the gradle build and maven build diverged, but i feel the maven builds maybe got neglected at some point.

**build specs**
```
 $ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/.../.sdkman/candidates/maven/current
Java version: 17.0.2, vendor: Oracle Corporation, runtime: /home/.../.sdkman/candidates/java/17.0.2-open
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-131-generic", arch: "amd64", family: "unix"

```

**Comment by rezekdan** [comment]
rerun it with maven 3.8.6 just to make sure, but same result

**Comment by marcingrzejszczak** [comment]
Yeah, Stream folks messed things up. I'll update this in a second

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud-samples/spring-cloud-contract-samples/commit/ea3ff99b3f9b8074e91ca9eb835617cbbfd64c95
