### ISSUE TITLE
beer-contracts sample doesn't build

### ISSUE THREAD

**Issue by jakub-bochenski** [spring-cloud-samples/spring-cloud-contract-samples#421]
On branch 4.0.x:

```
 ./mvnw clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: org.springframework.cloud:spring-cloud-dependencies:pom:2022.0.7-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype has elapsed or updates are forced @ line 53, column 16
```

**Comment by marcingrzejszczak** [comment]
That's because 4.0.x is only available with the commercial build

**Comment by jakub-bochenski** [comment]
What do you mean? I seem to be using SCC 4.x public build just fine

**Comment by marcingrzejszczak** [comment]
https://spring.io/projects/spring-cloud-contract#support 
![image](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/assets/3297437/677b795c-fef6-4c77-b162-572b4d4a51dc)

**Comment by jakub-bochenski** [comment]
Oh, having support cycles based on minor releases is awkward.

Anyhow, 4.0.x branch is still linked from current documentation e.g. https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/using.html#flows-cdc-contracts-external links to https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/4.0.x/consumer
