### ISSUE TITLE
Extend fromRequest.body with additional properties 

### ISSUE THREAD

**Issue by theburhan** [spring-cloud-samples/spring-cloud-contract-samples#43]
Is it possible to extend the fromRequest.body() with additional properties.
I have a case, where external system returns in the response the exact request body in addition to that an object. as an example

```Contract contractDsl = Contract.make {
	request {
		method 'GET'
		url('/api/v1/xxxx') {
			queryParameters {
				parameter("foo", "bar")
				parameter("foo", "bar2")
			}
		}
		headers {
			header(authorization(), "secret")
			header(authorization(), "secret2")
		}
		body(foo: "bar", baz: 5)
	}
	response {
		status OK()
		headers {
			header(authorization(), "foo ${fromRequest().header(authorization())} bar")
		}
		body(fromRequest().body().properties.put("id":"some_id"))
	}
}```

but that results in "null".

**Comment by marcingrzejszczak** [comment]
You can't do that.

**Comment by theburhan** [comment]
it would be nice, if anything similar can be supported. Because, such use cases are very likely to happen.

**Comment by marcingrzejszczak** [comment]
> Because, such use cases are very likely to happen.

You're the first person to ask for something like this.

**Comment by theburhan** [comment]
> > Because, such use cases are very likely to happen.
> 
> You're the first person to ask for something like this.

I'm sure, I will not be the last asking this ;)
