### ISSUE TITLE
Reactive Streamlistener not receiving messages from stubTrigger.trigger

### ISSUE THREAD

**Issue by kriskrishna** [spring-cloud-samples/spring-cloud-contract-samples#70]
this.stubTrigger.trigger("movie_created_v1");

@StreamListener
    public void processMovies(@Input(Sink.INPUT) Flux<Movie> movies){
        movies.subscribe( x -> {
            movieRepository.save(x).subscribe(m -> log.info("@@@@@@@@@@@@@@ saved message: @@@@@ " + m.toString()));
        });
    }

**Comment by kriskrishna** [comment]
StreamListenerMessageHandler is not kicking in to consume message from Stubrunner....
org.springframework.cloud.stream.binding.StreamListenerMessageHandler

**Comment by OlgaMaciaszek** [comment]
Hello @kriskrishna 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). 
Is this an issue with these samples? Please provide the steps to reproduce the issue.
